### ISSUE TITLE
List of activities

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#1]
## Value proposition
**As a** user
**I need** to see activities
**to be able to** know what I can do in Hamburg.

## Description
User should be able to scroll in order to see all ten list items.

<img width="150" alt="list of activities" src="https://user-images.githubusercontent.com/96734196/156578190-06760994-3099-40b1-bdb8-ff13e2cdd00a.png">

## Acceptance criteria
- [x] List can be scrolled

## Tasks
- [x] Create Component / List 
   - [x] Storybook
   - [x] Test
- [x] Add to app
- [x] GlobalStyles
- [x] Test on mobile device
- [x] Check accessibility
