### ISSUE TITLE
Delete activity

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#11]
## Value proposition
**As a** user
**I need** to have the opportunity to enter something wrong and therefore I need 
**to be able to** delete an entry.

## Description
<img width="150" alt="delete activity" src="https://user-images.githubusercontent.com/96734196/156610405-92f0b64f-d7e3-412c-9427-4cc9e051709b.png"> <img width="150" alt="delete activity (confirmation)" src="https://user-images.githubusercontent.com/96734196/156612235-244e4063-1b78-4468-a077-3449222ec78c.png">

## Acceptance criteria
- [x] bin button is displayed (delete button)
- [x] when delete button is clicked, component modal appears and asks for confirmation
   - [x] when clicked yes in modal, entry disappears from list
   - [x] when clicked no in modal, it disappears and user stays in the list

## Tasks
 - [x] Update component / Button (bin button)
   - [x] Storybook
   - [x] Test
 - [x] Update component / card (bin button)
   - [x] Storybook
   - [x] Test
- [x] Create component / Modal
   - [x] Storybook
   - [x] Test
- [x] Test on mobile device
- [x] Check accessibility
- [x] Adjust READ.me
