### ISSUE TITLE
Local storage

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#14]
## Value proposition
**As a** user
**I need** to save my activities
**to be able to** see them when reopen the app.

## Description
Add a local storage, so that the entered data will be saved for next visit.

## Acceptance criteria
- [x] entries are displayed when reopening browser

## Tasks
- [x] Add local storage 
- [x] Test on mobile device
- [x] Adjust READ.me
