### ISSUE TITLE
Upload picture

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#15]
## Value proposition
**As a** user
**I need** to upload a picture
**to be able to** have additional information in my activity, when I found it somewhere eg. a poster of an event.

## Description
<img width="502" alt="Upload picture" src="https://user-images.githubusercontent.com/96734196/159213546-7e31d0ad-95c8-44ab-9ed7-a997164e7318.png">

## Acceptance criteria
- [x] Picture can be uploaded in the form when entering a new and edit activity
   - [x] Picture is displayed in activity overview
   - [x] Picture is displayed in small version in front of the activity in activity list
   - [x] When no picture is uploaded, placeholder picture appears

## Tasks
- [x] Adjust Component Form
   - [x] Add picture upload
   - [x] Storybook
   - [x] Test
- [x] Adjust ActivityOverview Page
   - [x] Add picture
   - [x] Add pictures based on category which will be taken alternatively when no picture is uploaded
   - [x] Test
- [x] Adjust Comonent ActivityCard
   - [x] Add picture in front of activity name
   - [x] Add pictures based on category which will be taken alternatively when no picture is uploaded
   - [x] Storybook
   - [x] Test
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
