### ISSUE TITLE
Local storage error message

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#18]
## Value proposition
**As a** user
**I need** to have an information
**to be able to** understand why my saved activities are not shown.

## Description
<img width="150" alt="local storage error message" src="https://user-images.githubusercontent.com/96734196/156604466-6cd3d749-bf0e-40c3-9674-41a2fabdb5cf.png">

## Acceptance criteria
- [x] When local storage is not sending the stored data, send error message.

## Tasks
- [x] Add error boundary to local storage
   - [x] Test
- [x] Test on mobile device
