### ISSUE TITLE
add empty page for first use

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#19]
## Value proposition
**As a** user
**I need** to have an empty list
**to be able to** know that I do not have the data of someone else.

## Description
When a user is using the app the first time, an empty page needs to be shown.

## Acceptance criteria
- [ ] When using app the first time, no list should be shown but a text.

## Tasks
- [ ] Update Component / List 
   - [ ] Storybook
   - [ ] Test
- [ ] Add to app
