### ISSUE TITLE
Add favorite page

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#2]
## Value proposition
**As a** user
**I need** to check when an activity is done
**to be able to** either delete this activity or keep it in my inspire list.

## Description
<img width="350" alt="Add favorite page" src="https://user-images.githubusercontent.com/96734196/159115324-509d7a8e-fdc1-4d2f-aa7d-6bbbf2f45b53.png">

## Acceptance criteria
- [x] when clicking done modal opens and asks me if i want to keep the activity or not
   - [x] when keeping it, it will be bookmarked  with like
   - [x] when not, it will be bookmarked  with like
- [x] favorite page shows all bookmarked, toggle between like an not
- [x] navigation shows a star which leads to favorite page
- [x] home button is displayed in the upper right corner and leads to the friendlist page

## Tasks
- [x] Add check to the activity overview page
   - [x] Test
- [x] Create component/ DoneModal
   - [x] Storybook
   - [x] Test
- [x] Adjust component button (star)
   - [x] Storybook
   - [x] Move home button to the upper right corner
   - [x] Add star bottom left
      - [x] Add navigation
   - [x] Test
- [x] Create favorite page
   - [x] Add list for liked activities
   - [x] Test
- [x] add functionality to overview page
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
