### ISSUE TITLE
Interactive list with form (two pages)

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#22]
## Value proposition
**As a** user
**I need** have detailed information about the activity itself on a separate page
**to be able to** have a better overview.

## Description
<img width="300" alt="Interactive list with form (two pages) " src="https://user-images.githubusercontent.com/96734196/157431663-66e08848-9aea-4185-bd02-205b988afe60.png">

## Acceptance criteria
- [x] additional page: name of activity page
   - [x] when click on activity in start screen, name of activity page with details appears
   - [x] click on arrow, back to the start screen, position where user came from

## Tasks
- [x] Create name of activity page for detailed overview (display old Card content)
   - [x] make activity in start screen clickable and link it to name of activity page (Router)
   - [x] Test
- [x] Add Header to name of activity page and make it conditional (my activities / name of activity)
- [x] Update component / Button (add arrow)
   - [x] Storybook
- [x] Add button to my activity page
- [x] Test on mobile device
- [x] Check accessibility
- [x] Update README
