### ISSUE TITLE
Interactive list with form (three pages)

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#26]
## Value proposition
**As a** user
**I need** to have the form to add an activity on a separate page 
**to be able to** have have a better overview with only the list on my main page.

## Description
<img width="500" alt="Interactive list with form (three pages)" src="https://user-images.githubusercontent.com/96734196/157617857-493b9b2f-b99e-4445-85d3-23969ce9121a.png">

## Acceptance criteria
- [x] button on start page shows + 
   - [x] with Navigation via Router user comes to the form on new activity page
- [x] new activity page change header
   - [x] new page shows form
   - [x] header has an arrow button for going back to start page
   - [x] add button is clickable to save
      - [x] when add is clicked,  user comes back to home screen
      - [x] when add is clicked, new entry appears in the end of the list, where the scroll also leads to

## Tasks
- [x] Create component / Header (Refactor and add new header)
   - [x] Storybook
   - [x] Test
- [x] Update component / Button  (+)
   - [x] Storybook
   - [x] Test
- [x] Add + button to start page 
   - [x] Add new page with Form
   - [x]  Update form distancing
   - [x] Add Router to navigate to new page
      - [x] Update Header (new activity and arrow)
   - [x] Test
- [x] Test on mobile device
- [x] Check accessibility
- [x] Update README
