### ISSUE TITLE
Adjust Styling

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#32]
## Value proposition
**As a** user
**I need** to have a proper constant styling of the app
**to be able to** know what the app is used for and where I am able to click.

## Description
<img width="240" alt="Adjust Styling" src="https://user-images.githubusercontent.com/96734196/158228381-f2bc599e-196d-4e64-b72c-03b1c5018e61.png">

## Acceptance criteria
- [x] Header has to be everywhere and with the same styling
- [x] Footer has to be everywhere and with the same styling
- [x] Background picture on pages 
- [x] Form color transparent and therefore border

## Tasks
- [x] Adjust Component Header 
   - [x] make smaller font size
   - [x] place text without arrow back center
- [x] Create component Footer
   - [x] Add to pages
- [x] Add background picture to pages
- [x] Adjust Button 
   - [x] variants to make code clean
   - [x] Bin bigger
- [x] Test on mobile device 
- [x] Check accessibility
