### ISSUE TITLE
Add search page

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#35]
## Value proposition
**As a** user
**I need** to have a search page
**to be able to** search through all activities, not related by the entered friend.

## Description
<img width="250" alt="Add search page" src="https://user-images.githubusercontent.com/96734196/159114118-6a2b428e-e74b-452c-83e1-86a9c947c261.png">

## Acceptance criteria
- [x] new page shows a list of all activities
   - [x] when searching 
      - [x] finds entry
      - [x] error message that nothing is found
- [x] Home and Search button can be clicked with navigation
- [x] When activity is clicked, URL shows the way (:friend:activiy)

## Tasks
- [x] Adjust component Navigation(Home/ Search)
   - [x] Storybook
   - [x] Test
- [x] Add Search page
   - [x] Add Navigation button search and home
   - [x] Add navigation to each page 
   - [x] Add List of all activities
      - [x] Test
- [x] Create component/ Search
   - [x] Storybook
   - [x] Test
   - [x] Add to Search page
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
