### ISSUE TITLE
Add categories

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#36]
## Value proposition
**As a** user
**I need** to have categories in the form
**to be able to** give each a category to have a better overview.

## Description
<img width="400" alt="Add categories" src="https://user-images.githubusercontent.com/96734196/159113873-82961b28-f6e8-4e3f-b5fd-19e1cbf6630d.png">

## Acceptance criteria
- [x] Form includes an input for categories (dropdown)
   - [x] make other default when nothing is entered
- [x] ActivityOverview displays category

## Tasks
- [x] Adjust Component Form
   - [x] Add additional input
   - [x] Storybook
   - [x] make it drop down
   - [x] when nothing is chosen - default other
   - [x] Test
- [x] Adjust ActivityOverview Page
   - [x] Test
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
