### ISSUE TITLE
Add filter to search

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#37]
## Value proposition
**As a** user
**I need** to also have a filter on my search page
**to be able to** either search by word or filter.

## Description
<img width="300" alt="Add filter to search" src="https://user-images.githubusercontent.com/96734196/159114107-e7efdc06-c8f0-41a1-911b-0942436f74f7.png">

## Acceptance criteria
- [x] all activities page shows a list of all activities
   - [x] when filtering 
      - [x] search bar will be emptied
      - [x] default: all
      - [x] finds entries
      - [x] error message that nothing is found

## Tasks
- [x] Add component Tags to Search page
   - [x] Add filter function
   - [x] Set search to empty string
   - [x] Test
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
