### ISSUE TITLE
Filter/Search my favorites

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#38]
## Value proposition
**As a** user
**I need** to search and filter my favorite activities
**to be able to** get a faster result when looking for a new activity.

## Description
<img width="250" alt="Filter:Search my favorites" src="https://user-images.githubusercontent.com/96734196/159115710-e6fb954f-4ac6-4658-9fa0-2d69e6b6236b.png">

## Acceptance criteria
- [x] when searching
   - [x] finds entry
   - [x] error message that nothing is found
- [x] when filtering
   - [x]  search bar will be emptied
   - [x] default: all
   - [x] finds entries
   - [x] error message that nothing is found

## Tasks
- [x] Add component/ Search (already created)
- [x]  Add component Tags (already created)
   - [x] Add filter function
   - [x] Set search to empty string
   - [x] Test
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
