### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#46]
**As a** developer
**I need** to check and improve code
**to be able to** do a quick issue fixing.

## Description
Double check code if it could be refactored and if everything is same structured.

## Acceptance criteria
- [ ] everything is still working as before
- [ ] code is cleaner and more easy to read

## Tasks
- [ ] Go through each file and check:
   - [ ] possibility to refactor
      - [ ] e.g adjust component Form 
         - [ ] Create component Upload picture and import to form
         - [ ] Storybook
         - [ ] Test
   - [ ] is everything properly tested
   - [ ] everything up to date for accessibility
- [ ] Test on mobile device
