### ISSUE TITLE
Add friends

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#48]
## Value proposition
**As a** user
**I need** to add a friend separately
**to be able to** have no typos and hence that every activity will be displayed with this exact friend.

## Description
<img width="700" alt="Add a friend" src="https://user-images.githubusercontent.com/96734196/160338168-b93a8605-bd19-4bdd-95d4-1d7ab5a7162a.png">

## Acceptance criteria
- [x] when clicking on the friend-plus-icon a new page appears
   - [x] I can fill in a new form my friend
   - [x] underneath I see a list of all friends entered
- [x] in the activity form I can only choose friends, not write them in

## Tasks
- [x] Adjust navigation with friend-plus-icon 
   - [x] Storybook
   - [x] Test
- [x] Add new page
   - [x] Adjust navigation
   - [x] Test
- [x] Add new form to page
   - [x] input goes into list underneath
   - [x] add delete function
   - [x] Test
- [x] Adjust form so that friends can only be chosen (only one friend / activity)
   - [x] Storybook
   - [x] Test
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
