### ISSUE TITLE
Add delete to past activities

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#49]
## Value proposition
**As a** user
**I need** to delete also my past activities
**to be able to** have  a well sorted overview.

## Description
<img width="336" alt="Delete past activity" src="https://user-images.githubusercontent.com/96734196/160339043-f3dabf87-5331-409a-af28-5de87aff6deb.png">

## Acceptance criteria
- [x] delete button on past overview page
   - [x] when click delete same modal as in other delete function appears
   - [x] click delete -> delete, otherwise keep

## Tasks
- [x] Adjust overview page with delete button
   - [x] add functionality
   - [x] Test
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
