### ISSUE TITLE
Add a group

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#50]
## Value proposition
**As a** user
**I need** to also add a group 
**to be able to** add activities with a group.

## Description
<img width="624" alt="Add a group" src="https://user-images.githubusercontent.com/96734196/160339960-6b0fad28-dc4a-43c6-9d09-1c79764bd1ce.png">

## Acceptance criteria
- [x] Group-plus-icon  is visible (toggle between friend and group)
- [x] Group-plus-icon  is visible
- [x] when clicking on Group-plus-icon a new page appears
   - [x] the user can fill in a new form my group
- [x] in the activity form I can choose either a friend or a group, not write them in

## Tasks
- [x] Adjust navigation with group and Group-plus-icon 
   - [x] Storybook
   - [x] Test
- [x] Add new page
   - [x] Adjust navigation
   - [x] Test
- [x] Add new form to page
   - [x] add delete function
   - [x] Test
- [x] Adjust form so that friends and groups can only be chosen (only one friend/ group per activity)
   - [x] Storybook
   - [x] Test
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
