### ISSUE TITLE
Fix Issues

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#51]
## Value proposition
**As a** user
**I need** to have a proper working app
**to be able to** use it efficiently.

## Description
Adjust small issues which appeared after a while.

## Acceptance criteria
- [ ] explanation of app when empty
- [ ] Time out is visible with message when something is added
- [ ] nothing around Modal can be clicked

## Tasks
- [ ] Adjust empty message friends and group screen
- [ ] Adjust form
   - [ ] friends entry
   - [ ] save/ add button gets a message
   - [ ] Storybook
   - [ ] Test
- [ ] Adjust modal so that nothing around can be clicked
