### ISSUE TITLE
Interactive list with form (one page)

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#6]
## Value proposition
**As a** user
**I need** to add an activity
**to be able to** remember what I want to do.

## Description
Add form below the list for entries. List of entries can be scrolled.
After filling out and submitting, add entry to list above. The entry will be positioned at the very end of the list. In order to make it visible for the user, the list is automatically jumping down to this new entry.
 
<img width="215" alt="add activity to list (one page)" src="https://user-images.githubusercontent.com/96734196/156588675-11245e23-b8e6-4b5b-b4aa-1d98e3f15375.png"><img width="200" alt="empty screen" src="https://user-images.githubusercontent.com/96734196/156588845-83d8ab96-dc6d-45c1-a0fb-fb586e76046e.png">

## Acceptance criteria
- [x] name of activity is required 
- [x] name of person is not required
- [x] submit button should add an entry in the list at the bottom
- [x] the focus of the screen is going down to the new entry
- [x] When a user has no data entered yet, no list should be shown but a text.
- [x] in case one of the names is too long for one row, show ending with three dots (...)

## Tasks
- [x] Create Component / Button (submit) 
   - [x] Storybook
   - [x] Test
- [x] Create Component / Form
   - [x] Storybook
   - [x] Test
 - [x] Create Component / Card (form entries go in here)
   - [x] Storybook
   - [x] Test
 - [x] Update Component / List (add name/ shows empty list message)
   - [x] Storybook
   - [x] Test
- [x] Add to app
- [x] Test on mobile device
- [x] Check accessibility
- [x] Adjust READ.me
