### ISSUE TITLE
Add more details

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#7]
## Value proposition
**As a** user
**I need** to enter more details to an activity 
**to be able to** remind myself better.

## Description
<img width="452" alt="Add more details" src="https://user-images.githubusercontent.com/96734196/157619044-97e45f8b-a6c6-4adb-bb6e-820387c5017b.png">

## Acceptance criteria
- [x] new activity page adjust form
   - [x] form has more input fields 
      - [x] activity name (maxlength 50)
      - [x] friends name (maxlength 100)
      - [x] notes (maxlength 200)
      - [x] date 
      - [x] place (maxlength 50)
- [x] activity page (display input of form) 

## Tasks
- [x] Update component / Form (more input fields)
   - [x] Storybook
   - [x] Test
- [x] Update activity overview page (displays more details)
   - [x] Test
- [x] Test on mobile device
- [x] Check accessibility
- [x] Update README
