### ISSUE TITLE
Map friends and sort them

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#8]
## Value proposition
**As a** user
**I need** to see a sorted list of my friends
**to be able to** know which activities I have with whom.

## Description
<img width="532" alt="Map friends and sort them" src="https://user-images.githubusercontent.com/96734196/158017762-f0923e59-f13a-4620-a5a2-35c89ea83b47.png">

## Acceptance criteria
- [x] Start screen shows a list of friends
   - [x] activities labeled to no person are listed in 'I still need to plan...'
   - [x] activities labeled to a person are listed in belonging 'name of person'
   - [x] a number at the end of the row  is showing the number of activities with the specific person
   - [x] to do is on the first position and names are sorted by alphabet
- [x] when clicked on the name, navigated to persons page
   - [x] header is changing to the belonging clicked person
- [x] arrow is pushing user back to home screen

## Tasks
- [x] Create component / PersonCard
   - [x] Storybook
   - [x] Test
- [x] Create new page and make home screen
   - [x] Add a list with PersonCard
   - [x] Test
- [x] Update activity page (add arrow to friends)
   - [x] Test
- [x] Update new activity page
   - [x] Arrow once to person and once to specific activity
- [x] Test on mobile device
- [x] Check accessibility
- [x] Update README
