### ISSUE TITLE
Filter function for specific friend

### ISSUE THREAD

**Issue by JelenadlS** [JelenadlS/capstone-project#9]
## Value proposition
**As a** user
**I need** to have categories in the form
**to be able to** filter the activities planned with my friend by specific categories.

## Description
<img width="500" alt="filter function for specific friend" src="https://user-images.githubusercontent.com/96734196/159112990-f892c34c-614b-4647-ae5e-10d5c7703916.png">

## Acceptance criteria
- [x] FriendsActivity page includes a scrollable filter function
   - [x] When tag is clicked, only activities with this tag are visible
      - [x] all: all activities
      - [x] specific tag: only those activities are displayed which include this tag

## Tasks
 - [x] Adjust FriendsActivies page
   - [x] Add tags above list
   - [x] Make them scrollable
   - [x] Add filter function to specific tags
   - [x] No filter for tag 'all'
   - [x] Test
- [x] Test on mobile device 
- [x] Check accessibility
- [x] Update README
